version: "3.9"

services:
  jupyter:
    build: ./docker
    image: two-tower:latest
    command: >
      jupyter lab --ip=0.0.0.0 --port=8888
      --no-browser --allow-root --NotebookApp.token=''
    volumes:
      - ./:/workspace         # code + notebooks
      - data:/data            # raw datasets
      - models:/models        # trained checkpoints
      - logs:/logs            # tensorboard etc.
    ports:
      - "8888:8888"
      - "6006:6006"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all       # or "1", "2" …
              capabilities: [gpu]

volumes:
  data:
  models:
  logs: 