# Configuration for minimal testing with HuggingFace Hub integration and W&B
extends: configs/char_tower.yml

# Dataset path (extremely small dataset for testing)
data: data/processed/train_multi_pos_multi_neg_sample_10.parquet

# Training parameters (minimal for quick testing)
epochs: 1
batch_size: 32
device: cpu  # Use CPU for testing to avoid CUDA errors

# HuggingFace Hub settings
huggingface:
  push_to_hub: true
  repo_id: test-two-tower-temp
  private: true

# Weights & Biases settings
use_wandb: true
wandb:
  run_name: test_small_dataset
  project: two-tower-retrieval
  tags: ["test", "minimal"] 